sources:
  chart:
    type: helm
    repoURL:
      property: ghcrCharts
    repository: grafana/helm-charts
    chart: grafana
    targetRevision: 10.5.15
    properties:
      global.imageRegistry: dockerImages
manifests:
  properties:
    external-secrets.io/ExternalSecret/grafana-admin:
      /spec/secretStoreRef/name: secretStore
