sources:
  chart:
    type: helm
    repoURL:
      property: ghcrCharts
    repository: grafana-community/helm-charts
    chart: grafana
    targetRevision: "13.2.7"
    properties:
      global.imageRegistry: dockerImages
manifests:
  properties:
    external-secrets.io/ExternalSecret/grafana-admin:
      /spec/secretStoreRef/name: secretStore
