namespace: cert-manager
sources:
  chart:
    type: helm
    repoURL:
      property: quayCharts
    repository: jetstack/charts
    chart: cert-manager
    releaseName: cert-manager
    targetRevision: "v1.21.2"
    properties:
      imageRegistry: quayImages
