apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: grafana-admin
  dataFrom:
    - extract:
        key: grafana/admin
